name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Database
      run: |
        'mysql -e "create database codeception_test;"'
        'psql -c "create database codeception_test;" -U postgres'

    - name: Run test suite
      run: php ./vendor/bin/codecept run
